[project]
name = "github-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=0.1",
    "httpx>=0.27",
    "pydantic>=2",
    "fastapi>=0.115.12",
    "starlette>=0.46.1",
    "uvicorn>=0.34.0",
]
